services:
  reservation_back_service:
    container_name: 'reservation_back'
    build:
      context: .
    ports:
      - "8001:8000"
    networks:
      - my_network
    env_file:
      - .env

  reservation_db_service:
    container_name: 'reservation_db'
    image: postgres:16
    environment:
      POSTGRES_USER: reservation_user
      POSTGRES_PASSWORD: reservation_pass
      POSTGRES_DB: reservation-service
    ports:
      - "6432:5432"
    volumes:
      - pg-reservation-data:/var/lib/postgresql/data
    networks:
      - my_network


volumes:
  pg-reservation-data:


networks:
  my_network:
    external: true
